### ISSUE TITLE
(Arch Linux) arguments to dbus_connection_unref() were incorrect

### ISSUE THREAD

**Issue by cookiengineer** [mupen64plus/mupen64plus-ui-python#95] opened 2017-02-11 17:06 UTC
I seem to have the same SDL2 / D-Bus related error when using m64py. I wanted to open a separate issue, because everything is not dependent on upstream libraries and was built from source (AUR).

Relevant AUR packages are python-pysdl2, m64py with modifications (see [this PKGBUILD file](https://github.com/cookiengineer/abs/blob/master/aur/m64py/PKGBUILD))

```bash
$ m64py;

(mupen64plus acii logo)

M64Py - A frontend for Mupen64Plus version 0.2.4

process 19738: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file dbus-connection.c line 2822.
This is normally a bug in some application using the D-Bus library.
  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)
```

I also cannot find anything related to `dbus_current_generation` in the `/usr/include/dbus-1.0/dbus/*.h` files; if that helps.

The signature of `dbus_connection_unref()` is expected to be this one:

```bash
cd /usr/include/dbus-1.0/dbus;
grep -R "dbus_connection_unref" ./;

./dbus-connection.h:void               dbus_connection_unref                        (DBusConnection             *connection);
```

Relevant library versions: Built from stable versions today, a couple minutes ago.

- dbus 1.10.14-1 (from Arch Linux core)
- m64py v0.2.4 (from github releases)
- python-pysdl2 v0.9.5 (from bitbucket.org/marcusva/py-sdl2)

Relevant source code file of D-Bus:

https://cgit.freedesktop.org/dbus/dbus/tree/dbus/dbus-connection.c?id=449d6b313d2023360cf0af063cf23232901dd00b#n2822

What are the necessary steps to confirm that this bug is related to #91 ?

**Comment by cookiengineer** [comment] 2017-02-11 17:33
I also tried searching everything in `/usr/lib/python3.6/site-packages/` regarding dbus, connection and unref; but I've found not a single statement that seems to be anyhow related to the issue :-/

How can I do a stack trace with python in that scenario (I have no idea of python)?

**Comment by jwhendy** [comment] 2017-02-14 04:37
I'm getting the same. Just to reproduce what I'm seeing:
```
$ m64py
M64Py - A frontend for Mupen64Plus version 0.2.4

Frontend: INFO: ScreenSaver not available: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
process 1676: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file dbus-connection.c line 2822.
This is normally a bug in some application using the D-Bus library.
  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)
```

I happen to be migrating my arch install from one drive to another (same computer) and must be on an old install on the other drive as this was new to me. I checked and package version `0.2.3-5` works (also, only `sdl2` installed there, not `python-pysdl2`). I'm happy to dig/test if you need another assistant.

**Comment by bermond** [comment] 2017-02-18 22:50
Also having this issue are on Arch Linux x86_64.
It looks like it's the same as #91.

**Comment by akien-mga** [comment] 2017-02-20 18:10
> What are the necessary steps to confirm that this bug is related to #91 ?

Well looking at the error log this bug is exactly the same as #91. Why do you think it would have a different cause? But at least we know it can be reproduced on many distros with different stacks.

**Comment by vinipsmaker** [comment] 2017-05-20 18:47
It happens the same to me:

```
vinipsmaker ~ $ m64py 
 __  __                         __   _  _   ____  _            
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___  
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __| 
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \ 
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/ 
             |_|                                               

M64Py - A frontend for Mupen64Plus version 0.2.4

Frontend: INFO: ScreenSaver not available: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
process 1347: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file dbus-connection.c line 2822.
This is normally a bug in some application using the D-Bus library.
  D-Bus not built with -rdynamic so unable to print a backtrace
zsh: abort (core dumped)  m64py
```

**Comment by ibrokemypie** [comment] 2017-08-09 09:25
```
$ m64py

(python:2884): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(python:2884): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
 __  __                         __   _  _   ____  _            
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___  
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __| 
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \ 
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/ 
             |_|                                               

M64Py - A frontend for Mupen64Plus version 0.2.4

Frontend: INFO: ScreenSaver not available: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
process 2884: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file dbus-connection.c line 2822.
This is normally a bug in some application using the D-Bus library.
  D-Bus not built with -rdynamic so unable to print a backtrace
zsh: abort      m64py


```

**Comment by Videonauth** [comment] 2017-10-22 16:08
Happens to me too on Ubuntu 17.10 with vanilla-gnome-desktop on X

**Comment by joemaro** [comment] 2018-04-14 17:07
same error here:
```
19:03 ~ $  m64py 
qt5ct: using qt5ct plugin
 __  __                         __   _  _   ____  _            
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___  
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __| 
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \ 
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/ 
             |_|                                               

M64Py - A frontend for Mupen64Plus version 0.2.4

Invalid Context= "Apps" line for icon theme:  "/usr/share/icons/Arc/apps/symbolic/"
Invalid Context= "Mimetypes" line for icon theme:  "/usr/share/icons/Arc/mimetypes/symbolic/"
Invalid Context= "Mimetypes" line for icon theme:  "/usr/share/icons/Faba/symbolic/mimetypes/"
Icon theme "elementary" not found.
Icon theme "elementary" not found.
Frontend: INFO: ScreenSaver not available: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
Frontend: INFO: No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
dbus[21725]: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file dbus-connection.c line 2822.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
fish: “m64py” terminated by signal SIGABRT (Abort)
```

**Comment by gen2brain** [comment] 2020-04-12 10:58
Addressed in https://github.com/mupen64plus/mupen64plus-ui-python/commit/948c4d5a7b7440404370a36017674f09af642d6d

**Comment by TopHarp** [comment] 2020-11-16 12:29
i find a RE
 said : restart the messagebus service;
# /etc/init.d/messagebus start
Starting system message bus:                               [  OK  ]

**Comment by Unounited** [comment] 2020-12-29 17:51
Can anyone help me I get this error when running m64py:
libEGL warning: DRI2: failed to authenticate
qt5ct: using qt5ct plugin
 __  __                         __   _  _   ____  _            
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___  
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __| 
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \ 
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/ 
             |_|                                               

M64Py - A frontend for Mupen64Plus version 0.2.3

Frontend: INFO: ScreenSaver not available: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
Traceback (most recent call last):
  File "/usr/share/m64py/m64py/SDL2/dll.py", line 100, in <module>
    dll = _DLL("SDL2", ["SDL2", "SDL2-2.0"], os.getenv("PYSDL2_DLL_PATH"))
  File "/usr/share/m64py/m64py/SDL2/dll.py", line 51, in __init__
    raise RuntimeError("could not find any library for %s" % libinfo)
RuntimeError: could not find any library for SDL2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/m64py", line 57, in <module>
    from m64py.frontend.mainwindow import MainWindow
  File "/usr/share/m64py/m64py/frontend/mainwindow.py", line 30, in <module>
    from m64py.frontend.worker import Worker
  File "/usr/share/m64py/m64py/frontend/worker.py", line 27, in <module>
    from m64py.core.core import Core
  File "/usr/share/m64py/m64py/core/core.py", line 32, in <module>
    from m64py.core.vidext import vidext
  File "/usr/share/m64py/m64py/core/vidext.py", line 33, in <module>
    from m64py.SDL2 import SDL_WasInit, SDL_InitSubSystem, SDL_QuitSubSystem, SDL_INIT_VIDEO
  File "/usr/share/m64py/m64py/SDL2/__init__.py", line 2, in <module>
    from .dll import get_dll_file, _bind
  File "/usr/share/m64py/m64py/SDL2/dll.py", line 102, in <module>
    raise ImportError(exc)
ImportError: could not find any library for SDL2

Do I need something installed?

**Closed** 2024-10-20 11:55 UTC
