### ISSUE TITLE
segfault on launch

### ISSUE THREAD

**Issue by ghost** [mupen64plus/mupen64plus-ui-python#58] opened 2015-07-23 22:39 UTC
m64py segfaults almost immediately after launch:

![1](https://cloud.githubusercontent.com/assets/5460027/8863814/b926cd9e-3150-11e5-8eae-e550a40fec1b.png)

mupen64plus works just fine. My system is Fedora Linux 22 x86_64. This problem occurs identically whether I install the Fedora RPM package, or build it from source.

**Comment by gabriel-hackerdou** [comment] 2016-01-02 03:18
Facing same issue with Fedora 23.

**Comment by gabriel-hackerdou** [comment] 2016-01-02 06:38
It seems that there are some missing python libraries. Installing PyOpenGL package gives you an additional output before segfault:

M64Py - A frontend for Mupen64Plus version 0.2.3

INFO:OpenGL.acceleratesupport:OpenGL_accelerate module loaded
INFO:OpenGL.arrays.arraydatatype:Using accelerated ArrayDatatype
Violación de segmento (`core' generado)

**Comment by akien-mga** [comment] 2016-01-09 16:39
> It seems that there are some missing python libraries. Installing PyOpenGL package gives you an additional output before segfault

I can confirm this issue on Mageia 6, python 3 build with Qt5, mupen64plus 2.0 (I'm going to try 2.5 asap). I had a plain segfault without output, and after installing python3-opengl I also get:
```
Frontend: INFO: OpenGL_accelerate module loaded
Frontend: INFO: Using accelerated ArrayDatatype
Segmentation fault
```

**Comment by akien-mga** [comment] 2016-01-09 16:51
So far with some prints here and there I tracked down the issue to https://github.com/mupen64plus/mupen64plus-ui-python/blob/7c426c8/src/m64py/frontend/mainwindow.py#L202

To be sure I verified that reverting 7c426c8 does _not_ solve the issue (i.e. ```self.vidext``` is True anyway)

**Comment by akien-mga** [comment] 2016-01-09 16:54
Hm I just noticed that I have Qt 5.6.0 beta6 libraries but only python3-qt5 5.5.1, that might be a reason for the crash...

**Comment by akien-mga** [comment] 2016-01-09 16:55
(At any rate such non-intercepted segfaults are an issue that should be fixed IMO)

**Comment by gabriel-hackerdou** [comment] 2016-01-10 05:56
I'm trying to migrate QGLWidget to new QOpenGLWidget, using this Object I can avoid this segfault, but I get one when launching any ROM. 
I think it is related with PyOpenGL. I tried to make a sample program using QOpenGLWidget and I'm getting PyOpenGL error not supporting OpenGL 4.5 version.

**Comment by gabriel-hackerdou** [comment] 2016-01-10 06:41
I have Qt 5.5.1 and python-qt5 5.5.1
Trying to run this program also gives me a segfault: https://riverbankcomputing.com/pipermail/pyqt/2014-July/034542.html

**Comment by gabriel-hackerdou** [comment] 2016-01-21 02:38
I finally found what the issue is! This only happens with NVIDIA drivers. I found the following in a launchpad bug related to PyQT:

Peter Würtz (pwuertz) wrote on 2014-08-12: 

Apparently the PyQt application ends up loading the Mesa GL library (/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0) instead of the NVidia driver (/usr/lib/nvidia-331/libGL.so.331.38) that is loaded when importing PyOpenGL first.

The difference seems to be the library name when calling dlopen(). PyOpenGL tries to import "libGL.so.1", whereas PyQt imports "libGL.so", without the ".1" suffix.

A simple C application calling dlopen() and checking /proc/<pid>/maps shows that "libGL.so" points to the Mesa driver, whereas "libGL.so.1" ends up loading the NVidia driver.

-----

There is a simple workaround that was known by m64py developers since they use it in src/m64py/core/vidext.py

try:
    # nvidia hack
    from OpenGL import GL
    glimport = True
except ImportError:
    glimport = False

However, when m64py main window is created, an QOGLWidget is initialized when added to stack

self.stack.addWidget(self.glwidget)

For some reason in QT5, OpenGL context is also initialized, but this happens before the hack in vidext.py, resulting in a segfault.

The solution is to move Nvidia hack to src/m64py/frontend/mainwindow.py
By simply importing GL in mainwindow.py solves the issue.

**Comment by gen2brain** [comment] 2016-01-21 04:30
Hi,
I have no problem with including whatever fix/hack that can help users with this problem, but it would be nice if we can also find real reason why this happens.

That nvidia hack is there for some time. I use Gentoo, and I never found reason for that OpenGL import (PyQt4/PyQt5, doesn't matter). Everything works as it should without it, but on debian ( and maybe fedora, I am not sure)  this is needed if you have nvidia card. I don't have nvidia anymore, just intel, so I can't test, it just works for me, with latest python, PyQt etc.

Whatever you find is appreciated, but I really can't confirm that it is working. If someone with same problem and nvidia card can also test this fix and if it works I will add the changes.

Thanks,
Milan

**Comment by gabriel-hackerdou** [comment] 2016-01-21 15:45
Hi!
I found the root cause. The reason of this happening in some distros and not in others is driver packaging.
After running ldconfig I can see the following:

libGL.so.1 (libc6,x86-64) => /lib64/libGL.so.1
libGL.so.1 (libc6) => /lib/libGL.so.1
libGL.so (libc6,x86-64) => /lib64/libGL.so
libGL.so (libc6) => /lib/libGL.so

In my system (Fedora 23) /lib64/libGL.so is a link to mesa's libGL.so.1.2.0, while the others are links to Nvidia's libGL.so.352.63.

After having all links pointing to Nvidia's libGL.so.352.63 the problem is gone. I can run m64py removing nvidia hack stuff.

**Comment by bmbeverst** [comment] 2016-05-28 17:42
gabriel-hackerdou@ fix worked for me.

Ubuntu 16.04 LTS xenial

M64Py - A frontend for Mupen64Plus version 0.2.3
Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.5.0

sudo ldconfig -v | grep libGL
        libGLU.so.1 -> libGLU.so.1.3.1
/sbin/ldconfig.real: /lib/x86_64-linux-gnu/ld-2.23.so is the dynamic linker, ignoring

        libGLU.so.1 -> libGLU.so.1.3.1
        libGLEW.so.1.13 -> libGLEW.so.1.13.0
        libGLESv1_CM.so.1 -> libGLESv1_CM.so.1
        libGLX.so.0 -> libGLX.so.0
        libGLESv2.so.2 -> libGLESv2.so.2
        libGLESv2_nvidia.so.2 -> libGLESv2_nvidia.so.361.42
        libGL.so.1 -> libGL.so.1.0.0
        libGLX_nvidia.so.0 -> libGLX_nvidia.so.361.42
        libGLdispatch.so.0 -> libGLdispatch.so.0
/sbin/ldconfig.real: Cannot stat /usr/lib32/nvidia-361/libOpenGL.so: No such file or directory
        libGLESv1_CM_nvidia.so.1 -> libGLESv1_CM_nvidia.so.361.42
/sbin/ldconfig.real: /lib32/ld-2.23.so is the dynamic linker, ignoring

        libGLESv1_CM.so.1 -> libGLESv1_CM.so.1
        libGLX.so.0 -> libGLX.so.0
        libGLESv2.so.2 -> libGLESv2.so.2
        libGLESv2_nvidia.so.2 -> libGLESv2_nvidia.so.361.42
        libGL.so.1 -> libGL.so.1.0.0
        libGLX_nvidia.so.0 -> libGLX_nvidia.so.361.42
        libGLdispatch.so.0 -> libGLdispatch.so.0
        libGLESv1_CM_nvidia.so.1 -> libGLESv1_CM_nvidia.so.361.42
/sbin/ldconfig.real: /libx32/ld-2.23.so is the dynamic linker, ignoring

**Comment by gen2brain** [comment] 2020-04-10 14:48
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.

**Closed by gen2brain** 2020-04-10 14:48 UTC
