### ISSUE TITLE
SDL configure control (Aborted) linux

### ISSUE THREAD

**Issue by aluismarte** [mupen64plus/mupen64plus-ui-python#92] opened 2017-02-01 17:45 UTC
Crash on click configure control.

**Comment by gen2brain** [comment] 2017-02-02 02:47
What version do you use, some info, crash info, anything?

**Comment by aluismarte** [comment] 2017-02-02 23:41
Version 0.2.4

This is normally a bug in some application using the D-Bus library.
process 18971: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file ../../../dbus/dbus-connection.c line 2822.
This is normally a bug in some application using the D-Bus library.
Unhandled Python exception
Aborted

Linux Debian Stretch

**Comment by gen2brain** [comment] 2017-02-03 00:07
Duplicate of #91 .

**Closed** 2020-04-10 14:46 UTC
