### ISSUE TITLE
Input configuration issues

### ISSUE THREAD

**Issue by brianvanderburg2** [mupen64plus/mupen64plus-ui-python#48] opened 2015-05-10 01:20 UTC
I've been having this issue since 0.1.6, where when I edit the input configuration and close the program, it never seems to actually save and always reverts to something else.  With the 0.2.3 version, I am getting an error from Python3:

```
Traceback (most recent call last):
  File "/usr/share/m64py/m64py/frontend/input.py", line 61, in closeEvent
    self.save_config()
  File "/usr/share/m64py/m64py/frontend/input.py", line 135, in save_config
    self.save_opts()
  File "/usr/share/m64py/m64py/frontend/input.py", line 243, in save_opts
    self.config.set_parameter("name", devicename.encode())
AttributeError: 'bytes' object has no attribute 'encode'
```

I am using Debian Jessie (recently Debian Wheezy) x64 Linux 3.16 and Mupen64Plus 2.0.0

**Comment by brianvanderburg2** [comment] 2015-05-10 01:34
I have found that by changing the following file I can get it to work:

/usr/share/m64py/m64py/frontend/input.py:
```
    def save_opts(self):
        devicename = self.device_map.get(self.device)
        if devicename:
            if not isinstance(devicename, bytes):
                devicename = devicename.encode()

            self.config.set_parameter("name", devicename)
```

The reason is, it seems, sometimes the device name is in bytes already.  When I configure the input, I get the following two devices:

Keyboard/Mouse
Joystick 0 (b'DragonRise Inc.    Generic USB Joystick  ')

So it seems like, when I set it to Keyboard/Mouse, the result from self.device_map.get is not in bytes, but when I set it to use the USB gamepad, the result from self.device_map.get is in bytes and calling encode throws the exception.  The change makes it only call encode if it is not already in bytes.

**Comment by brianvanderburg2** [comment] 2015-05-10 04:13
It is still not saving the input configuration correctly.  The problem seems to be located somewhere within get_sdl_key.  It seems like it is returning 0 for all inputs.  I can make the configuration use any key during editing of input (hat, button, axis, or key). It seems to save any type of input for the analog stick configuration.  For the other inputs, it only seems to save them if they are keys.

**Comment by conchurnavid** [comment] 2015-05-10 06:43
This is a duplicate of bug #2

**Comment by secretrobotron** [comment] 2015-09-12 19:36
This does actually help the input library write to the config file. However, mupen64plus still re-writes config, and changes only some of the gamepad mapping.

**Comment by slimjim27** [comment] 2015-10-15 05:13
heres my dilema i cant seem to find the folder /usr/share/mupen64plus and i know i downloaded and installed mupen64plus from gdeb pack instllr. now to clarify, what does show up is my m64py folder. is it possible to do it from this folder and if so ill need a run through.

**Comment by Mazamazine** [comment] 2016-09-03 01:21
Same problem here with a fresh ubuntu 16.4 
brianvanderburg2 solution coupled with this https://github.com/mupen64plus/mupen64plus-ui-python/issues/2 solved the problem. Modifying directly mupen64plus.cfg didn't work as it was overwritten...

**Comment by gen2brain** [comment] 2017-01-19 05:16
It should be fixed in new release.

**Closed by gen2brain** 2017-01-19 05:16 UTC
