### ISSUE TITLE
erro to open in arch linux

### ISSUE THREAD

**Issue by Derei-Ramos** [mupen64plus/mupen64plus-ui-python#204] opened 2022-07-09 06:18 UTC
![image](https://user-images.githubusercontent.com/74409904/178094259-21f05e4a-16a9-4c4f-b257-7e62956858d6.png)

**Comment by jaxad0127** [comment] 2022-09-24 23:21
I'm getting this too, Python 3.10.7. I've attached the backtrace from GDB, and stdout (-vv).
[backtrace.txt](https://github.com/mupen64plus/mupen64plus-ui-python/files/9639730/backtrace.txt)
[stdout.txt](https://github.com/mupen64plus/mupen64plus-ui-python/files/9639734/stdout.txt)

**Comment by frealgagu** [comment] 2022-10-04 01:24
[#191 ](url)

It's caused by integer cast.

It was solved in:
https://github.com/mupen64plus/mupen64plus-ui-python/commit/516e89102e50ed9ec4634d020aa6a3f7dc12baf8
and
https://github.com/mupen64plus/mupen64plus-ui-python/commit/ae94cf124c7a0d564f9a736efd9882495fc82ea3

Also, latest version of AUR package contains the fix.

**Comment by jaxad0127** [comment] 2022-10-04 15:31
The GUI is loading for me now. Thank you.

**Comment by gen2brain** [comment] 2024-10-20 12:05
Please try with the new release, this should be fixed.

**Closed by gen2brain** 2024-10-20 12:05 UTC
