### ISSUE TITLE
[Arch Linux] DBus Error

### ISSUE THREAD

**Issue by AppIns** [mupen64plus/mupen64plus-ui-python#102] opened 2017-03-18 19:36 UTC
I get this error when I try to start m64py with a command line. I can start the program as root, but that doesn't allow you to do a lot of things

```
 __  __                         __   _  _   ____  _            
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___  
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __| 
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \ 
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/ 
             |_|                                               

M64Py - A frontend for Mupen64Plus version 0.2.4

Frontend: INFO: ScreenSaver not available: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
process 25353: arguments to dbus_connection_unref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file dbus-connection.c line 2822.
This is normally a bug in some application using the D-Bus library.
  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)
```

**Comment by gen2brain** [comment] 2017-03-18 20:07
duplicate of #91

**Closed by gen2brain** 2017-03-18 20:07 UTC
