### ISSUE TITLE
Lubuntu 22.04.1 LTS : list of roms empty

### ISSUE THREAD

**Issue by Estariel** [mupen64plus/mupen64plus-ui-python#207] opened 2022-10-02 06:31 UTC
hello,
i use m64-py but my list of roms is empty.
i use refresh button : list is empty.

my foder of Rom is : 
drwxrwxrwx 2 jude jude 20480 oct  1 21:51 N64

my file roms is:
-rwxrwxrwx 1 jude jude 10767951 mai 21  2020 '007 - GoldenEye (E).zip'
-rwxrwxrwx 1 jude jude 26577294 mai 21  2020 '007 - The World Is Not Enough (E).zip'
-rwxrwxrwx 1 jude jude 11910588 mai 21  2020 '1080 Snowboarding (JU).zip'
-rwxrwxrwx 1 jude jude 11311037 mai 21  2020 '1080 TenEighty Snowboarding (E).zip'
-rwxrwxrwx 1 jude jude 29942397 jui 22  2020 '40 Winks (Europe) (En,Es,It) (Proto).zip'
-rwxrwxrwx 1 jude jude  9067145 mai 21  2020 'AeroFighters Assault (E).zip'
-rwxrwxrwx 1 jude jude  3588147 mai 21  2020 'Aero Gauge (E).zip'
-rwxrwxrwx 1 jude jude 30283751 mai 21  2020 'Aidyn Chronicles - The First Mage (E).zip'
-rwxrwxrwx 1 jude jude  6846042 mai 21  2020 'Airboarder 64 (E).zip'
-rwxrwxrwx 1 jude jude 15445090 mai 21  2020 'All-Star Baseball 2000 (E).zip'
-rwxrwxrwx 1 jude jude 15438067 mai 21  2020 'All Star Baseball 2001 (U).zip'
-rwxrwxrwx 1 jude jude 11755723 mai 21  2020 'All-Star Baseball 99 (E).zip'
-rwxrwxrwx 1 jude jude  3552097 mai 21  2020 'All Star Tennis 99 (E).zip'
-rwxrwxrwx 1 jude jude 13942101 mai 21  2020 'Armorines - Project S.W.A.R.M. (E).zip'

can  help me   ???
regards

**Comment by noabody** [comment] 2022-12-30 18:19
Duplicate of #201, as noted in [comment](https://github.com/mupen64plus/mupen64plus-ui-python/pull/201#issuecomment-1153095043)

See [201.patch](https://github.com/mupen64plus/mupen64plus-ui-python/pull/201.patch) if you need a work around right now.

**Comment by Estariel** [comment] 2023-02-26 09:37
thx i applied patch.
but il dont view all cature for all games in list of games.

why ?

**Comment by autofire372** [comment] 2024-09-17 19:57
A new mupen64plus release happened back in July. This can probably be fixed now.

**Comment by gen2brain** [comment] 2024-09-18 12:35
@autofire372 Sure, I will update it when I find the time.

**Comment by gen2brain** [comment] 2024-10-12 13:56
Code is now updated for the latest mupen64plus, migrated to Qt6, Wayland is supported, bugs are fixed, etc. I will release a new version these days.

**Closed by gen2brain** 2024-10-12 13:56 UTC

**Comment by Estariel** [comment] 2024-10-15 20:22
thx

Le dim. 13 oct. 2024 à 00:56, Milan Nikolic ***@***.***> a
écrit :
